"""add_book_and_writers_tables

Revision ID: 6e3a18f82c5a
Revises: 
Create Date: 2023-01-05 14:54:20.234633

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '6e3a18f82c5a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('books',
                    sa.Column('id', mysql.BIGINT(unsigned=True), autoincrement=True, nullable=False),
                    sa.Column('title', mysql.VARCHAR(length=255), nullable=False),
                    sa.Column('writer_id', mysql.BIGINT(unsigned=True), nullable=False),
                    sa.Column('description', mysql.TEXT(), nullable=True),
                    sa.Column('publish_date', sa.DATE(), server_default=sa.text('(CURRENT_DATE())'), nullable=True),
                    sa.Column('rating', mysql.TINYINT(unsigned=True), nullable=True),
                    sa.Column('cover_file', mysql.VARCHAR(length=255), nullable=True),
                    sa.Column('book_file', mysql.VARCHAR(length=255), nullable=True),
                    sa.Column('genres', mysql.TEXT(), nullable=True),
                    sa.Column('created_at', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'),
                              nullable=False),
                    sa.Column('updated_at', mysql.TIMESTAMP(),
                              server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=False),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(op.f('ix_books_updated_at'), 'books', ['updated_at'], unique=False)
    op.create_table('writers',
                    sa.Column('id', mysql.BIGINT(unsigned=True), autoincrement=True, nullable=False),
                    sa.Column('name', mysql.VARCHAR(length=255), nullable=False),
                    sa.Column('lastname', mysql.VARCHAR(length=255), nullable=False),
                    sa.Column('born', sa.DATE(), server_default=sa.text('(CURRENT_DATE())'), nullable=False),
                    sa.Column('died', sa.DATE(), nullable=True),
                    sa.Column('created_at', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'),
                              nullable=False),
                    sa.Column('updated_at', mysql.TIMESTAMP(),
                              server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=False),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(op.f('ix_writers_updated_at'), 'writers', ['updated_at'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_writers_updated_at'), table_name='writers')
    op.drop_table('writers')
    op.drop_index(op.f('ix_books_updated_at'), table_name='books')
    op.drop_table('books')
    # ### end Alembic commands ###
