"""add_users_table

Revision ID: fcc9c1c84fd7
Revises: 6e3a18f82c5a
Create Date: 2023-01-09 16:53:54.521031

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'fcc9c1c84fd7'
down_revision = '6e3a18f82c5a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
                    sa.Column('id', mysql.BIGINT(unsigned=True), autoincrement=True, nullable=False),
                    sa.Column('username', mysql.VARCHAR(length=255), nullable=False),
                    sa.Column('name', mysql.VARCHAR(length=255), nullable=False),
                    sa.Column('lastname', mysql.VARCHAR(length=255), nullable=False),
                    sa.Column('email', mysql.VARCHAR(length=255), nullable=False),
                    sa.Column('is_active', sa.BOOLEAN(), nullable=False),
                    sa.Column('created_at', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'),
                              nullable=False),
                    sa.Column('updated_at', mysql.TIMESTAMP(),
                              server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=False),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(op.f('ix_users_updated_at'), 'users', ['updated_at'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_updated_at'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
